module.exports = {
  "page": 1,
  "results": [
    {
      "id": 419704,
      "video": false,
      "vote_count": 1185,
      "vote_average": 6.1,
      "title": "Ad Astra",
      "release_date": "2019-09-17",
      "original_language": "en",
      "original_title": "Ad Astra",
      "genre_ids": [
        12,
        18,
        9648,
        878,
        53
      ],
      "backdrop_path": "/5BwqwxMEjeFtdknRV792Svo0K1v.jpg",
      "adult": false,
      "overview": "The near future, a time when both hope and hardships drive humanity to look to the stars and beyond. While a mysterious phenomenon menaces to destroy life on planet Earth, astronaut Roy McBride undertakes a mission across the immensity of space and its many perils to uncover the truth about a lost expedition that decades before boldly faced emptiness and silence in search of the unknown.",
      "poster_path": "/xBHvZcjRiWyobQ9kxBhO6B2dtRI.jpg",
      "popularity": 200.971,
      "media_type": "movie"
    },
    {
      "id": 466272,
      "video": false,
      "vote_count": 3160,
      "vote_average": 7.5,
      "title": "Once Upon a Time… in Hollywood",
      "release_date": "2019-07-25",
      "original_language": "en",
      "original_title": "Once Upon a Time… in Hollywood",
      "genre_ids": [
        35,
        18,
        53
      ],
      "backdrop_path": "/aQLygZOIKai6aaiBAeeKpIWO5nc.jpg",
      "adult": false,
      "overview": "Los Angeles, 1969. TV star Rick Dalton, a struggling actor specialized in westerns, and stuntman Cliff Booth, his best friend, try to survive to a constantly changing movie industry. Dalton is neighbor of the young and promising actress and model Sharon Tate, who has just married the prestigious Polish director Roman Polanski…",
      "poster_path": "/8j58iEBw9pOXFD2L0nt0ZXeHviB.jpg",
      "popularity": 132.804,
      "media_type": "movie"
    },
    {
      "id": 522938,
      "video": false,
      "vote_count": 752,
      "vote_average": 5.9,
      "title": "Rambo: Last Blood",
      "release_date": "2019-09-19",
      "original_language": "en",
      "original_title": "Rambo: Last Blood",
      "genre_ids": [
        28,
        18,
        53
      ],
      "backdrop_path": "/spYx9XQFODuqEVoPpvaJI1ksAVt.jpg",
      "adult": false,
      "overview": "After fighting his demons for decades, John Rambo now lives in peace on his family ranch in Arizona, but his rest is interrupted when Gabriela, the granddaughter of his housekeeper María, disappears after crossing the border into Mexico to meet her biological father. Rambo, who has become a true father figure for Gabriela over the years, undertakes a desperate and dangerous journey to find her.",
      "poster_path": "/kTQ3J8oTTKofAVLYnds2cHUz9KO.jpg",
      "popularity": 124.411,
      "media_type": "movie"
    },
    {
      "id": 398978,
      "video": false,
      "vote_count": 1268,
      "vote_average": 8,
      "title": "The Irishman",
      "release_date": "2019-11-01",
      "original_language": "en",
      "original_title": "The Irishman",
      "genre_ids": [
        80,
        18,
        36
      ],
      "backdrop_path": "/ww5aGS5H2tUtckxFFNOJE2790S7.jpg",
      "adult": false,
      "overview": "Pennsylvania, 1956. Frank Sheeran, a war veteran of Irish origin who works as a truck driver, accidentally meets mobster Russell Bufalino. Once Frank becomes his trusted man, Bufalino sends him to Chicago with the task of helping Jimmy Hoffa, a powerful union leader related to organized crime, with whom Frank will maintain a close friendship for nearly twenty years.",
      "poster_path": "/mbm8k3GFhXS0ROd9AD1gqYbIFbM.jpg",
      "popularity": 113.333,
      "media_type": "movie"
    },
    {
      "id": 474350,
      "video": false,
      "vote_count": 2415,
      "vote_average": 6.8,
      "title": "It Chapter Two",
      "release_date": "2019-09-04",
      "original_language": "en",
      "original_title": "It Chapter Two",
      "genre_ids": [
        18,
        14,
        27
      ],
      "backdrop_path": "/8moTOzunF7p40oR5XhlDvJckOSW.jpg",
      "adult": false,
      "overview": "27 years after overcoming the malevolent supernatural entity Pennywise, the former members of the Losers' Club, who have grown up and moved away from Derry, are brought back together by a devastating phone call.",
      "poster_path": "/zfE0R94v1E8cuKAerbskfD3VfUt.jpg",
      "popularity": 108.976,
      "media_type": "movie"
    },
    {
      "id": 492188,
      "video": false,
      "vote_count": 477,
      "vote_average": 8.3,
      "title": "Marriage Story",
      "release_date": "2019-11-06",
      "original_language": "en",
      "original_title": "Marriage Story",
      "genre_ids": [
        18,
        10749
      ],
      "backdrop_path": "/4PCO7tewIGnE6ySjVf2DbJ3pjqq.jpg",
      "adult": false,
      "overview": "A stage director and an actor struggle through a grueling, coast-to-coast divorce that pushes them to their personal extremes.",
      "poster_path": "/bm6zKJjKYKrIy3dcnOLk0kF85cl.jpg",
      "popularity": 126.498,
      "media_type": "movie"
    },
    {
      "id": 431580,
      "video": false,
      "vote_count": 262,
      "vote_average": 6.9,
      "title": "Abominable",
      "release_date": "2019-09-19",
      "original_language": "en",
      "original_title": "Abominable",
      "genre_ids": [
        12,
        16,
        35,
        10751
      ],
      "backdrop_path": "/tLCDKsXo6D84IVFanoElosSEKdp.jpg",
      "adult": false,
      "overview": "A group of misfits encounter a young Yeti named Everest, and they set off to reunite the magical creature with his family on the mountain of his namesake.",
      "poster_path": "/20djTLqppfBx5WYA67Y300S6aPD.jpg",
      "popularity": 84.058,
      "media_type": "movie"
    },
    {
      "id": 384018,
      "video": false,
      "vote_count": 2142,
      "vote_average": 6.6,
      "title": "Fast & Furious Presents: Hobbs & Shaw",
      "release_date": "2019-08-01",
      "original_language": "en",
      "original_title": "Fast & Furious Presents: Hobbs & Shaw",
      "genre_ids": [
        28,
        12,
        35
      ],
      "backdrop_path": "/qAhedRxRYWZAgZ8O8pHIl6QHdD7.jpg",
      "adult": false,
      "overview": "Ever since US Diplomatic Security Service Agent Hobbs and lawless outcast Shaw first faced off, they just have swapped smacks and bad words. But when cyber-genetically enhanced anarchist Brixton's ruthless actions threaten the future of humanity, both join forces to defeat him. (A spin-off of “The Fate of the Furious,” focusing on Johnson's Luke Hobbs and Statham's Deckard Shaw.)",
      "poster_path": "/kvpNZAQow5es1tSY6XW2jAZuPPG.jpg",
      "popularity": 68.72,
      "media_type": "movie"
    },
    {
      "id": 330457,
      "video": false,
      "vote_count": 923,
      "vote_average": 7,
      "title": "Frozen II",
      "release_date": "2019-11-20",
      "original_language": "en",
      "original_title": "Frozen II",
      "genre_ids": [
        12,
        16,
        10402,
        10751
      ],
      "backdrop_path": "/xJWPZIYOEFIjZpBL7SVBGnzRYXp.jpg",
      "adult": false,
      "overview": "Elsa, Anna, Kristoff and Olaf head far into the forest to learn the truth about an ancient mystery of their kingdom.",
      "poster_path": "/pjeMs3yqRmFL3giJy4PMXWZTTPa.jpg",
      "popularity": 276.007,
      "media_type": "movie"
    },
    {
      "id": 540901,
      "video": false,
      "vote_count": 658,
      "vote_average": 6.2,
      "title": "Hustlers",
      "release_date": "2019-09-12",
      "original_language": "en",
      "original_title": "Hustlers",
      "genre_ids": [
        35,
        80,
        18
      ],
      "backdrop_path": "/mSQjVoZJaZkaHpdLIahh04bfGDr.jpg",
      "adult": false,
      "overview": "A crew of savvy former strip club employees band together to turn the tables on their Wall Street clients.",
      "poster_path": "/zBhv8rsLOfpFW2M5b6wW78Uoojs.jpg",
      "popularity": 74.124,
      "media_type": "movie"
    },
    {
      "id": 475557,
      "video": false,
      "vote_count": 6368,
      "vote_average": 8.4,
      "title": "Joker",
      "release_date": "2019-10-02",
      "original_language": "en",
      "original_title": "Joker",
      "genre_ids": [
        80,
        18,
        53
      ],
      "backdrop_path": "/n6bUvigpRFqSwmPp1m2YADdbRBc.jpg",
      "adult": false,
      "overview": "During the 1980s, a failed stand-up comedian is driven insane and turns to a life of crime and chaos in Gotham City while becoming an infamous psychopathic crime figure.",
      "poster_path": "/udDclJoHjfjb8Ekgsd4FDteOkCU.jpg",
      "popularity": 129.032,
      "media_type": "movie"
    },
    {
      "id": 423204,
      "video": false,
      "vote_count": 799,
      "vote_average": 5.8,
      "title": "Angel Has Fallen",
      "release_date": "2019-08-21",
      "original_language": "en",
      "original_title": "Angel Has Fallen",
      "genre_ids": [
        28,
        53
      ],
      "backdrop_path": "/k2WyDw2NTUIWnuEs5gT7wgrCQg6.jpg",
      "adult": false,
      "overview": "After a treacherous attack, Secret Service agent Mike Banning is charged with attempting to assassinate President Trumbull. Chased by his own colleagues and the FBI, Banning begins a race against the clock to clear his name.",
      "poster_path": "/fapXd3v9qTcNBTm39ZC4KUVQDNf.jpg",
      "popularity": 53.349,
      "media_type": "movie"
    },
    {
      "id": 420818,
      "video": false,
      "vote_count": 3861,
      "vote_average": 7.1,
      "title": "The Lion King",
      "release_date": "2019-07-12",
      "original_language": "en",
      "original_title": "The Lion King",
      "genre_ids": [
        12,
        18
      ],
      "backdrop_path": "/nRXO2SnOA75OsWhNhXstHB8ZmI3.jpg",
      "adult": false,
      "overview": "Simba idolizes his father, King Mufasa, and takes to heart his own royal destiny. But not everyone in the kingdom celebrates the new cub's arrival. Scar, Mufasa's brother—and former heir to the throne—has plans of his own. The battle for Pride Rock is ravaged with betrayal, tragedy and drama, ultimately resulting in Simba's exile. With help from a curious pair of newfound friends, Simba will have to figure out how to grow up and take back what is rightfully his.",
      "poster_path": "/2bXbqYdUdNVa8VIWXVfclP2ICtT.jpg",
      "popularity": 60.274,
      "media_type": "movie"
    },
    {
      "id": 499701,
      "video": false,
      "vote_count": 382,
      "vote_average": 6.4,
      "title": "Dora and the Lost City of Gold",
      "release_date": "2019-08-08",
      "original_language": "en",
      "original_title": "Dora and the Lost City of Gold",
      "genre_ids": [
        12,
        35,
        10751
      ],
      "backdrop_path": "/61sbyO47yIpsMFyLhY1MWcqjg1Q.jpg",
      "adult": false,
      "overview": "Dora, a girl who has spent most of her life exploring the jungle with her parents, now must navigate her most dangerous adventure yet: high school. Always the explorer, Dora quickly finds herself leading Boots (her best friend, a monkey), Diego, and a rag tag group of teens on an adventure to save her parents and solve the impossible mystery behind a lost Inca civilization.",
      "poster_path": "/xvYCZ740XvngXK0FNeSNVTJJJ5v.jpg",
      "popularity": 61.629,
      "media_type": "movie"
    },
    {
      "id": 512200,
      "video": false,
      "vote_count": 173,
      "vote_average": 6.8,
      "title": "Jumanji: The Next Level",
      "release_date": "2019-12-04",
      "original_language": "en",
      "original_title": "Jumanji: The Next Level",
      "genre_ids": [
        28,
        12,
        35,
        14
      ],
      "backdrop_path": "/zTxHf9iIOCqRbxvl8W5QYKrsMLq.jpg",
      "adult": false,
      "overview": "Spencer returns to the world of Jumanji, prompting his friends, his grandfather and his grandfather’s friend to enter a different and more dangerous version to save him.",
      "poster_path": "/l4iknLOenijaB85Zyb5SxH1gGz8.jpg",
      "popularity": 382.985,
      "media_type": "movie"
    },
    {
      "id": 567609,
      "video": false,
      "vote_count": 552,
      "vote_average": 6.8,
      "title": "Ready or Not",
      "release_date": "2019-08-21",
      "original_language": "en",
      "original_title": "Ready or Not",
      "genre_ids": [
        35,
        27,
        9648,
        53
      ],
      "backdrop_path": "/j8uPZSPjKYzHlN2B4NhPQVWWZ5x.jpg",
      "adult": false,
      "overview": "A bride's wedding night takes a sinister turn when her eccentric new in-laws force her to take part in a terrifying game.",
      "poster_path": "/vOl6shtL0wknjaIs6JdKCpcHvg8.jpg",
      "popularity": 52.631,
      "media_type": "movie"
    },
    {
      "id": 453405,
      "video": false,
      "vote_count": 828,
      "vote_average": 5.7,
      "title": "Gemini Man",
      "release_date": "2019-10-02",
      "original_language": "en",
      "original_title": "Gemini Man",
      "genre_ids": [
        28,
        18,
        14,
        878,
        53
      ],
      "backdrop_path": "/c3F4P2oauA7IQmy4hM0OmRt2W7d.jpg",
      "adult": false,
      "overview": "Ageing assassin, Henry Brogen tries to get out of the business but finds himself in the ultimate battle—fighting his own clone who is 25 years younger than him, and at the peak of his abilities.",
      "poster_path": "/uTALxjQU8e1lhmNjP9nnJ3t2pRU.jpg",
      "popularity": 50.28,
      "media_type": "movie"
    },
    {
      "id": 501170,
      "video": false,
      "vote_count": 573,
      "vote_average": 7.1,
      "title": "Doctor Sleep",
      "release_date": "2019-10-30",
      "original_language": "en",
      "original_title": "Doctor Sleep",
      "genre_ids": [
        18,
        14,
        27
      ],
      "backdrop_path": "/1nm0sk8UUx9jHCTHuMKe2jkt4Pn.jpg",
      "adult": false,
      "overview": "A traumatized, alcoholic Dan Torrance meets Abra, a kid who also has the ability to \"shine.\" He tries to protect her from the True Knot, a cult whose goal is to feed off of people like them in order to remain immortal.",
      "poster_path": "/p69QzIBbN06aTYqRRiCOY1emNBh.jpg",
      "popularity": 68.651,
      "media_type": "movie"
    },
    {
      "id": 429617,
      "video": false,
      "vote_count": 5313,
      "vote_average": 7.6,
      "title": "Spider-Man: Far from Home",
      "release_date": "2019-06-28",
      "original_language": "en",
      "original_title": "Spider-Man: Far from Home",
      "genre_ids": [
        28,
        12,
        878
      ],
      "backdrop_path": "/5myQbDzw3l8K9yofUXRJ4UTVgam.jpg",
      "adult": false,
      "overview": "Peter Parker and his friends go on a summer trip to Europe. However, they will hardly be able to rest - Peter will have to agree to help Nick Fury uncover the mystery of creatures that cause natural disasters and destruction throughout the continent.",
      "poster_path": "/4q2NNj4S5dG2RLF9CpXsej7yXl.jpg",
      "popularity": 56.767,
      "media_type": "movie"
    },
    {
      "id": 299534,
      "video": false,
      "vote_count": 10447,
      "vote_average": 8.3,
      "title": "Avengers: Endgame",
      "release_date": "2019-04-24",
      "original_language": "en",
      "original_title": "Avengers: Endgame",
      "genre_ids": [
        28,
        12,
        878
      ],
      "backdrop_path": "/7RyHsO4yDXtBv1zUU3mTpHeQ0d5.jpg",
      "adult": false,
      "overview": "After the devastating events of Avengers: Infinity War, the universe is in ruins due to the efforts of the Mad Titan, Thanos. With the help of remaining allies, the Avengers must assemble once more in order to undo Thanos' actions and restore order to the universe once and for all, no matter what consequences may be in store.",
      "poster_path": "/or06FN3Dka5tukK1e9sl16pB3iy.jpg",
      "popularity": 43.549,
      "media_type": "movie"
    }
  ],
  "total_pages": 1000,
  "total_results": 20000
};